Spring Boot Security
Litvynets/-Online-Book-store pull request #11
Opened 2024-11-14 10:40 UTC by Litvynets

password: "securePassword1234"

2024-11-14 11:13 UTC, Elena-Bruyako requested changes
see comments

2024-11-14 11:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Role.java
> +
redundant empty line

2024-11-14 11:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    private Set<Role> roles;
```suggestion
    private Set<Role> roles = new HashSet<>();
```

2024-11-14 11:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +
```
@Override
    public boolean isEnabled() {
        return !isDeleted;
    }
```

2024-11-14 11:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/repository/user/UserRepository.java
> +    @Query("SELECT u FROM User u JOIN FETCH u.roles WHERE u.email = :email")
it's better to use
```suggestion
    @EntityGraph(attributePaths = "roles")
```

2024-11-14 11:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/security/CustomUserDetailService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("Can't find user by email: "
```suggestion
                .orElseThrow(() -> new EntityNotFoundException("Can't find user by email: "
```

2024-11-14 11:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/user/impl/UserServiceImpl.java
> +    private static final Role.RoleName DEFAULT_ROLE = Role.RoleName.ROLE_USER;
redundant constant, you can use enum directly

2024-11-15 07:48 UTC, liliia-ponomarenko approved these changes
Good job! A few minor comments ;)

2024-11-15 07:48 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/controller/BookController.java
> +    @PreAuthorize("hasAnyRole('ROLE_ADMIN', 'ROLE_USER')")
In your solution, USER is the default role for each registered user. It means that ADMIN also has a USER role. So validating the USER role is enough for such endpoints

2024-11-15 07:48 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/repository/user/UserRepository.java
> +    Optional<User> findByEmail(@Param("email") String email);
```suggestion
    Optional<User> findByEmail(String email);
```
redundant annotation

2024-11-15 07:48 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/03-create-user-table.yaml
> +                  type: BIT
```suggestion
                  type: tinyint(1) 
```
(optional)

2024-11-15 07:48 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/04-create-roles-table.yaml
> +                  name: Id
```suggestion
                  name: id
```

2024-11-15 07:48 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/04-create-roles-table.yaml
> +                  value: ROLE_USER
add one empty line to the end of the file (check other files)

2025-07-29 19:58 UTC, merged